# Generated by Django 4.0 on 2023-01-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='cpa',
            new_name='ca',
        ),
    ]
