# Generated by Django 4.0 on 2023-01-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_symptom_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='person_name',
        ),
    ]
